# Generated by Django 2.0.7 on 2019-07-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
