# Generated by Django 2.2.3 on 2019-09-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0003_sentnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentnotice',
            name='key',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
