# Generated by Django 4.0.5 on 2022-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0004_auto_20190902_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sentnotice',
            name='id',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sentnotice',
            name='key',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
