# Generated by Django 2.0.7 on 2018-07-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
