# Generated by Django 2.0.7 on 2018-07-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0002_notice_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='pub_date',
        ),
    ]
