# Generated by Django 2.0.7 on 2019-07-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0003_remove_notice_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(),
        ),
    ]
