# Generated by Django 2.0.7 on 2019-07-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0004_auto_20190715_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.CharField(max_length=4096),
        ),
    ]
