# Generated by Django 2.0.7 on 2019-07-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0005_auto_20190716_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(),
        ),
    ]
