# Generated by Django 2.0.7 on 2019-07-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0007_botuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotUser',
        ),
    ]
