# Generated by Django 2.2.3 on 2019-09-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0008_delete_botuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='key',
            field=models.BigIntegerField(default=0),
        ),
    ]
