# Generated by Django 2.2.3 on 2019-09-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0009_auto_20190902_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='key',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
