# Generated by Django 2.2.3 on 2019-09-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0010_auto_20190902_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='title',
        ),
    ]
