# Generated by Django 2.2.13 on 2022-06-08 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notices', '0013_auto_20210205_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
